version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:cached
      - ./src/app/design:/var/www/html/app/design:cached
      - ./src/app/etc:/var/www/html/app/etc:cached
      - ./src/composer.json:/var/www/html/composer.json:cached
      - ./src/composer.lock:/var/www/html/composer.lock:cached
      - ./src/grunt-config.json.sample:/var/www/html/grunt-config.json:cached
      - ./src/Gruntfile.js.sample:/var/www/html/Gruntfile.js:cached
      - ./src/dev/tools/grunt/configs:/var/www/html/dev/tools/grunt/configs:cached
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src/package.json.sample:/var/www/html/package.json:cached
      #- ./src/auth.json:/var/www/html/auth.json:cached
      #- ./src/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./src/patches:/var/www/html/patches:cached
      #- ./src/var/log:/var/www/html/var/log:cached
      #- ./src/var/report:/var/www/html/var/report:cached
      - ./extensions/services-connector/ServicesConnector:/var/www/html/app/code/Magento/ServicesConnector:consistent
      - ./extensions/services-id/ServicesId:/var/www/html/app/code/Magento/ServicesId:consistent
      - ./extensions/services-id/ServicesIdGraphQlServer:/var/www/html/app/code/Magento/ServicesIdGraphQlServer:consistent
      - ./extensions/services-id/ServicesIdLayout:/var/www/html/app/code/Magento/ServicesIdLayout:consistent
      - ./extensions/data-services/DataServices:/var/www/html/app/code/Magento/DataServices:consistent
      - ./extensions/data-services/DataServicesMultishipping:/var/www/html/app/code/Magento/DataServicesMultishipping:consistent
      - ./extensions/commerce-data-export/CatalogDataExporter:/var/www/html/app/code/Magento/CatalogDataExporter:consistent
      - ./extensions/commerce-data-export/CatalogInventoryDataExporter:/var/www/html/app/code/Magento/CatalogInventoryDataExporter:consistent
      - ./extensions/commerce-data-export/CatalogUrlRewriteDataExporter:/var/www/html/app/code/Magento/CatalogUrlRewriteDataExporter:consistent
      - ./extensions/commerce-data-export/ConfigurableProductDataExporter:/var/www/html/app/code/Magento/ConfigurableProductDataExporter:consistent
      - ./extensions/commerce-data-export/BundleProductDataExporter:/var/www/html/app/code/Magento/BundleProductDataExporter:consistent
      - ./extensions/commerce-data-export/DataExporter:/var/www/html/app/code/Magento/DataExporter:consistent
      - ./extensions/commerce-data-export/ParentProductDataExporter:/var/www/html/app/code/Magento/ParentProductDataExporter:consistent
      - ./extensions/commerce-data-export/ProductVariantDataExporter:/var/www/html/app/code/Magento/ProductVariantDataExporter:consistent
      - ./extensions/commerce-data-export/QueryXml:/var/www/html/app/code/Magento/QueryXml:consistent
      - ./extensions/commerce-data-export/ScopesDataExporter:/var/www/html/app/code/Magento/ScopesDataExporter:consistent
      - ./extensions/commerce-data-export-ee/ProductOverrideDataExporter:/var/www/html/app/code/Magento/ProductOverrideDataExporter:consistent
      - ./extensions/saas-export/SaaSCatalog:/var/www/html/app/code/Magento/SaaSCatalog:consistent
      - ./extensions/saas-export/SaaSCommon:/var/www/html/app/code/Magento/SaaSCommon:consistent
      - ./extensions/saas-export/SaaSScopes:/var/www/html/app/code/Magento/SaaSScopes:consistent
      - ./extensions/product-recommendations/ProductRecommendationsLayout:/var/www/html/app/code/Magento/ProductRecommendationsLayout:consistent
      - ./extensions/product-recommendations/PageBuilderProductRecommendations:/var/www/html/app/code/Magento/PageBuilderProductRecommendations:consistent
      - ./extensions/product-recommendations/VisualProductRecommendations:/var/www/html/app/code/Magento/VisualProductRecommendations:consistent
      - ./extensions/product-recommendations-admin/ProductRecommendationsAdmin:/var/www/html/app/code/Magento/ProductRecommendationsAdmin:consistent
      - ./extensions/product-recommendations-admin/ProductRecommendationsSyncAdmin:/var/www/html/app/code/Magento/ProductRecommendationsSyncAdmin:consistent
      - ./extensions/catalog-sync-admin/CatalogSyncAdmin:/var/www/html/app/code/Magento/CatalogSyncAdmin:consistent
      - ./extensions/magento-live-search/LiveSearch:/var/www/html/app/code/Magento/LiveSearch:consistent
      - ./extensions/magento-live-search/LiveSearchAdapter:/var/www/html/app/code/Magento/LiveSearchAdapter:consistent
      - ./extensions/magento-live-search/LiveSearchStorefrontPopover:/var/www/html/app/code/Magento/LiveSearchStorefrontPopover:consistent
      - ./extensions/magento-live-search/LiveSearchMetrics:/var/www/html/app/code/Magento/LiveSearchMetrics:consistent
      - ./extensions/magento-live-search/LiveSearchTerms:/var/www/html/app/code/Magento/LiveSearchTerms:consistent
      - ./extensions/data-solutions-magento-bff/GraphQlServer:/var/www/html/app/code/Magento/GraphQlServer:consistent
      - ./extensions/data-solutions-magento-bff/AdminGraphQlServer:/var/www/html/app/code/Magento/AdminGraphQlServer:consistent
      #- ./extensions/data-solutions-magento-bff/ExternalSchemaGraphQlServer:/var/www/html/app/code/Magento/ExternalSchemaGraphQlServer:consistent

  phpfpm:
    env_file: env/magento.env
    volumes: *appvolumes

## ####################################################################################################
## Uncomment the lines below to add 'Elastic Search' to run integration tests in local dev environment
## Some integration tests require a running instance of elastic search, otherwise, will break.
## ####################################################################################################
#  elastic:
#    image: elasticsearch:7.9.3
#    hostname: elastic
#    ports:
#      - "9200:9200"
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
